'use strict';
const hosts=[{name:'web-server-01',ip:'10.0.1.10',status:'healthy',cpu:24,memory:48,latency:8},{name:'app-server-02',ip:'10.0.1.21',status:'warning',cpu:67,memory:89,latency:14},{name:'db-primary-01',ip:'10.0.2.10',status:'healthy',cpu:42,memory:64,latency:4},{name:'edge-router-01',ip:'10.0.0.1',status:'warning',cpu:18,memory:32,latency:42},{name:'worker-node-01',ip:'10.0.3.11',status:'healthy',cpu:36,memory:51,latency:11},{name:'worker-node-02',ip:'10.0.3.12',status:'healthy',cpu:29,memory:46,latency:9}];
const events=[
{id:'demo-auth',time:'Preview',category:'authentication',title:'Sign-in activity',severity:'info',host:'Demo device',user:'Sample user',evidence:'Your agent’s successful and failed sign-in events will appear here.',risk:'No real event has been collected.'},
{id:'demo-system',time:'Preview',category:'system',title:'System activity',severity:'info',host:'Demo device',user:'Sample user',evidence:'Your agent’s system and service activity will appear here.',risk:'No real event has been collected.'},
{id:'demo-files',time:'Preview',category:'files',title:'File changes',severity:'info',host:'Demo device',user:'Sample user',evidence:'Your agent’s file creation, modification, and deletion events will appear here.',risk:'No real event has been collected.'},
{id:'demo-app',time:'Preview',category:'applications',title:'Application activity',severity:'info',host:'Demo device',user:'Sample user',evidence:'Your agent’s application and process activity will appear here.',risk:'No real event has been collected.'}
];
let selectedEvent=null;
const $=id=>document.getElementById(id);let selected=null,busy=false,history=[],endpoint=localStorage.getItem('telemetry-chat-endpoint')||'';let controller=null;
function context(){return {dataMode:'sample',timeRangeHours:Number($('period').value),selectedHost:selected,hosts:[],events,selectedEvent,alerts:[]};}
function render(){ $('stats').innerHTML=[['Authentication','♡','Sign-ins & access'],['System','✧','Services & system events'],['Files','▧','File changes & activity'],['Applications','❋','Apps & processes']].map(([l,v,n],i)=>`<div class="stat category${i}"><div class="statvalue">${v}</div><p class="statlabel">${l}</p><p class="statnote">${n}</p><span class="empty-count">No data yet</span></div>`).join('');renderEvents(); }
function renderEvents(){const filtered=events.filter(e=>($('event-category').value==='all'||e.category===$('event-category').value)&&($('event-severity').value==='all'||e.severity===$('event-severity').value)&&(!selected||e.host===selected.name));$('event-rows').innerHTML=filtered.length?filtered.map(e=>`<tr><td>${e.time}</td><td>${e.category[0].toUpperCase()+e.category.slice(1)}</td><td class="event-action"><button class="hostbtn" data-event="${e.id}">${e.title}</button><small>${e.host} · ${e.user}</small></td><td><span class="severity ${e.severity}">${e.severity}</span></td></tr>`).join(''):'<tr><td colspan="4">No sample events match these filters.</td></tr>';}
function selectEvent(id){const event=events.find(e=>e.id===id);if(!event)throw Error('Unknown event');selectedEvent=event;$('event-detail').textContent=event.title+' · '+event.evidence+' Review: '+event.risk;$('chat-context').textContent=event.category+' · '+event.id+' · '+event.host;return context();}
$('event-category').onchange=renderEvents;$('event-severity').onchange=renderEvents;
document.addEventListener('click',e=>{const ev=e.target.closest('[data-event]');if(ev)selectEvent(ev.dataset.event);const prompt=e.target.closest('[data-prompt]');if(prompt){$('chat-input').value=prompt.dataset.prompt;send();}});
$('period').onchange=render;
function addMessage(role,text,error=false){const div=document.createElement('div');div.className='msg '+role+(error?' error':'');const label=document.createElement('div');label.className='role';label.textContent=role==='user'?'YOU':'ASSISTANT';div.append(label,document.createTextNode(text));$('messages').append(div);$('messages').scrollTop=$('messages').scrollHeight;return div;}
function demoReply(prompt){if(selectedEvent)return selectedEvent.evidence+'\n\nThis is a demo preview. Your agent is not connected yet.';return 'Your dashboard brings four types of activity together: authentication, system, files, and applications. Once your agent is connected, its collected events can appear in the activity feed.\n\nThere is no real telemetry yet. This is a scripted preview response; an AI backend can be connected later.';}
async function send(){const text=$('chat-input').value.trim();if(!text||busy)return;busy=true;$('send').disabled=true;$('chat-input').value='';addMessage('user',text);history.push({role:'user',content:text});const pending=addMessage('assistant',endpoint?'Waiting for your backend…':'Reading sample telemetry…');controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),30000);try{let reply;if(endpoint){const response=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({messages:history,telemetry:context()}),signal:controller.signal});if(!response.ok)throw Error(`Backend returned ${response.status}`);const result=await response.json();if(typeof result.reply!=='string'||!result.reply.trim())throw Error('Backend must return a nonempty reply string');reply=result.reply;}else reply=demoReply(text);pending.remove();addMessage('assistant',reply);history.push({role:'assistant',content:reply});}catch(error){pending.remove();history.pop();addMessage('assistant',(error.name==='AbortError'?'The request timed out.':error.message)+ ' Your message was not answered. Check the backend URL and CORS configuration, then try again.',true);}finally{clearTimeout(timeout);busy=false;$('send').disabled=false;controller=null;}}
$('chat-form').onsubmit=e=>{e.preventDefault();send();};$('chat-input').onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();send();}};
function resetChat(){if(busy)return;history=[];$('messages').replaceChildren();addMessage('assistant','Hi, I’m your telemetry assistant. Ask about authentication events, system activity, file changes, applications, or security alerts.\n\n'+(endpoint?'Your configured backend will receive your message and sample telemetry context.':'You’re viewing a demo with sample telemetry and scripted responses.'));}
$('clear-chat').onclick=resetChat;
function updateConnection(){ $('endpoint').value=endpoint;$('chat-mode').textContent=endpoint?'Custom backend configured':'Demo responses';$('connection-status').textContent=endpoint?'Configured, not verified. Messages and sample telemetry will be sent to this URL.':'No backend connected. Never enter an API key here.';}
$('connection-form').onsubmit=e=>{e.preventDefault();if(busy){$('connection-status').textContent='Wait for the current reply before changing the connection.';return;}const value=$('endpoint').value.trim();try{const url=new URL(value);if(url.protocol!=='https:')throw Error('Use an HTTPS backend URL.');endpoint=url.href;localStorage.setItem('telemetry-chat-endpoint',endpoint);updateConnection();resetChat();}catch(e){$('connection-status').textContent=e.message;}};
$('demo-reset').onclick=()=>{if(busy)return;endpoint='';localStorage.removeItem('telemetry-chat-endpoint');updateConnection();resetChat();};
$('clock').textContent=new Date().toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'});render();updateConnection();resetChat();
const mc=document.modelContext;const life=new AbortController();if(mc?.registerTool){Promise.resolve(mc.registerTool({name:'read_telemetry_snapshot',description:'Read the dashboard demo state. No actual collected telemetry is available yet.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>context()},{signal:life.signal})).catch(()=>{});window.addEventListener('pagehide',()=>life.abort(),{once:true});}
